# Generated by Django 3.1.2 on 2020-10-18 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('jobdescription', models.TextField(blank=True, default='job desc', null=True)),
                ('jobid', models.CharField(blank=True, max_length=200, null=True)),
                ('joblocation_address', models.CharField(blank=True, max_length=200, null=True)),
                ('jobtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('numberofpositions', models.IntegerField(blank=True, default=0, null=True)),
                ('payrate', models.CharField(blank=True, max_length=200, null=True)),
                ('postdate', models.DateField(default=datetime.date.today)),
                ('site_name', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.CharField(blank=True, max_length=200, null=True)),
                ('uniq_id', models.CharField(blank=True, max_length=200, null=True)),
                ('job_exp_cat', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
